server:
  port: 8083
spring:
  application:
    name: feign-client-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
# Log Output to a file
logging:
  file:
    path: "${user.dir}/${spring.application.name}}/log/"
    name: "${spring.application.name}.log"